config/routes.rb
Rails.application.routes.draw do

  get "up", to: "rails/health#show", as: :rails_health_check

  namespace :api do
    resources :entries
  end

  resources :comments
  resources :decider_lists, shallow: true do
    resources :decider_list_items, only: %i[new create destroy]
  end
  resources :entries
  resources :entry_batches, only: %i[new create]
  resources :inventory_items
  resources :notes
  resources :pages
  resources :users
  resources :post_photos, only: %i[create destroy]
  resources :post_access_grants, only: %i[create]

  resources :print_batches, only: :index do
    collection do
      get :entries
      get :posts
    end
  end

  resources :posts

  resources :photos, except: %i[new create]
  resources :photo_batches, only: :create

  get 'pick', to: 'decider_list_picker#index'
  get 'pick/:id', to: 'decider_list_picker#new'
  post 'pick/:id', to: 'decider_list_picker#create'

  resources :sessions
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  get 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new', as: 'login'

  root to: 'pages#index'

end

app/models/note.rb
class Note < ApplicationRecord

  acts_as_taggable_on :note_tags

  belongs_to :user, default: -> { Current.user }

  def self.tags
    taggings = ActsAsTaggableOn::Tagging.where(context: 'note_tags')
    ActsAsTaggableOn::Tag.joins(:taggings).merge(taggings).order(taggings_count: :desc).distinct
  end

  def suggested_tags
    self.class.tags.where.not(id: note_tag_ids)
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @notes = Note.all
    if params[:user_id].present?
      @notes = @notes.where(user_id: params[:user_id])
    else
      @notes = Current.user.notes
    end
    if params[:kind].present?
      @notes = @notes.where(kind: params[:kind])
    end
    if params[:term].present?
      @notes = @notes.where(Note.arel_table[:body].matches("%#{params[:term].to_s.downcase}%"))
    end
    if params[:tag].present?
      @notes = @notes.tagged_with(params[:tag], on: :note_tags)
    end
    @notes =
      case params[:finished].to_s
      when 'Finished'
        @notes.where.not(finished_at: nil)
      when 'Unfinished', ''
        @notes.where(finished_at: nil)
      else
        @notes
      end
    if params[:random]
      @notes = @notes.where(id: @notes.sample.try(:id))
    end
    @notes = @notes.order(Note.arel_table[:updated_at].desc)
    @notes = @notes.page(params[:page])
  end

  def new
    @note = Note.new
  end

  def create
    @note = Current.user.notes.new(safe_params)
    if @note.save
      redirect_to [:edit, @note], notice: 'Note saved.'
    else
      render :new
    end
  end

  def show
    @note = Note.find(params[:id])
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    if @note.update(safe_params)
      redirect_to [:edit, @note], notice: 'Note saved.'
    else
      render :edit
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to :notes, notice: 'Note destroyed.'
  end

  private

  def safe_params
    params.permit(note: [
      :body,
      :finished_at,
      :kind,
      :meta,
      :note_tag_list,
      :title,
      :user_id,
    ])[:note]
  end

  def authorized?
    Current.user&.father?
  end

end

app/views/notes/_form.html.haml
= form_with model: @note do |f|
  - if f.object.errors.any?
    .alert.alert-danger= f.object.errors.full_messages.to_sentence
  .mb-3
    = f.label :title, class: 'form-label'
    = f.text_field :title, class: 'form-control', tabindex: 1
  .mb-3{ data: { controller: "tag-inserter" } }
    = f.label :kind, class: 'form-label'
    - Current.user.notes.pluck(:kind).uniq.compact.each_with_index do |kind, i|
      = link_to kind, "#", data: { action: "tag-inserter#insert" }, class: 'btn btn-secondary btn-sm'
    = f.text_field :kind, class: 'form-control', tabindex: 2, data: { tag_inserter_target: "input" }
  .mb-3
    = f.label :body, class: 'form-label'
    = f.hidden_field :body, id: 'trix-editor-content'
    <trix-editor input="trix-editor-content" autofocus="true"></trix-editor>
  .mb-3
    = f.label :meta, class: 'form-label'
    = f.text_area :meta, rows: 3, class: 'form-control', tabindex: 4
  .mb-3{ data: { controller: "tag-inserter" } }
    = f.label :note_tag_list, class: 'form-label'
    %p
      - f.object.suggested_tags.limit(9).each do |tag|
        = link_to tag.name, "#", data: { action: "tag-inserter#insert" }, class: 'btn btn-secondary btn-sm'
    = f.text_field :note_tag_list, value: f.object.note_tag_list.to_s, class: 'form-control', tabindex: 4,
      data: { tag_inserter_target: "input" }
  .mb-3
    = f.submit 'Save', class: 'btn btn-primary'
    = link_to 'Cancel', :notes, class: 'btn btn-secondary'

app/views/notes/edit.html.haml
- title 'Edit Note'

= render 'form'

app/views/notes/index.html.haml
- title 'Notes'

- content_for :sidebar do

  .d-grid.gap-2
    = link_to [:new, :note], class: 'btn btn-success' do
      %i.bi-plus-lg
      New Note
    = link_to [:notes, { finished: 'Finished' }], class: 'btn btn-warning' do
      %i.bi-file-earmark-fill
      Finished Notes

  %hr

  %h3 Search
  = form_with url: :notes, method: :get, role: 'form' do |f|
    .mb-3
      = f.label :user_id, class: 'form-input'
      = f.select :user_id, User.where(role: %w(father mother)).map { |user| [user.name, user.id] }, { selected: params[:user_id] || Current.user.id.to_s }, class: 'form-select'
    .mb-3
      = f.label :kind, class: 'form-input'
      = f.select :kind, [nil] + Note.pluck(:kind).uniq.compact, { selected: params[:kind] }, class: 'form-select'
    .mb-3
      = f.label :term, class: 'form-input'
      = f.text_field :term, value: params[:term], class: 'form-control', placeholder: 'Search'
    .mb-3
      = f.label :finished, class: 'form-input'
      = f.select :finished, %w(Unfinished Finished Either), { selected: params[:finished] }, { class: 'form-select' }
    .form-check
      = f.check_box :random, checked: !params[:random].to_i.zero?, class: 'form-check-input', id: 'search-random-checkbox'
      = f.label :random, class: 'form-check-label', for: 'search-random-checkbox'
    .mb-3.d-grid.gap-2
      = f.submit 'Search', class: 'btn btn-primary'

  - if Note.note_tag_counts.present?
    %hr
    - tag_counts = Note.tag_counts_on(:note_tags).order(taggings_count: :desc)
    = render partial: 'shared/tag_list', locals: { path: :notes, tag_counts: tag_counts, total_count: Note.count }

- if @notes.empty?
  .alert.alert-warning
    %h2 No results found
    %p Maybe search for something else?
- else
  - @notes.each do |note|
    .mb-3
      %strong
        = link_to note, class: 'text-reset' do
          #{note.kind}: #{note.title}
      - note.note_tag_list.each do |tag_name|
        = link_to tag_name, [:notes, { tag: tag_name }], class: 'text-reset badge bg-secondary ms-2'

  = paginate @notes

app/views/notes/new.html.haml
- title 'New Note'

= render 'form'

app/views/notes/show.html.haml
- title @note.title

- content_for :sidebar do
  .d-grid.gap-2
    = link_to [:edit, @note], class: 'btn btn-info' do
      %i.bi-pencil-fill
        Edit
    - if @note.finished_at.present?
      = button_to [@note, { note: { finished_at: nil } }], method: :patch, class: 'btn btn-warning' do
        %i.bi-check-lg
        Unfinish
    - else
      = button_to [@note, { note: { finished_at: Time.zone.now } }], method: :patch, class: 'btn btn-warning' do
        %i.bi-check-lg
        Finish
    = button_to @note, class: 'btn btn-danger', method: :delete, data: { turbo_confirm: 'Are you sure you want to delete this note?' } do
      %i.bi-trash-fill
      Delete

  - if @note.note_tags.present?
    .panel.panel-default
      .panel-heading
        %h3.panel-title Tags
      .panel-body
        .list-group{ style: 'margin-top: 0.5em' }
          - @note.note_tag_list.each do |tag_name|
            = link_to tag_name, notes_path(tag: tag_name), class: 'list-group-item'

.row
  .col-md-12
    %h2.h2= @note.title
    = @note.body.html_safe