config/routes.rb
Rails.application.routes.draw do

  get "up", to: "rails/health#show", as: :rails_health_check

  namespace :api do
    resources :entries
  end

  resources :comments
  resources :decider_lists, shallow: true do
    resources :decider_list_items, only: %i[new create destroy]
  end
  resources :entries
  resources :entry_batches, only: %i[new create]
  resources :inventory_items
  resources :notes
  resources :pages
  resources :users
  resources :post_photos, only: %i[create destroy]
  resources :post_access_grants, only: %i[create]

  resources :print_batches, only: :index do
    collection do
      get :entries
      get :posts
    end
  end

  resources :posts

  resources :photos, except: %i[new create]
  resources :photo_batches, only: :create

  get 'pick', to: 'decider_list_picker#index'
  get 'pick/:id', to: 'decider_list_picker#new'
  post 'pick/:id', to: 'decider_list_picker#create'

  resources :sessions
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  get 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new', as: 'login'

  root to: 'pages#index'

end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord

  acts_as_taggable_on :inventory_item_tags

  has_many :inventory_item_photos
  has_many :photos, through: :inventory_item_photos

  validates :name, presence: true

  scope :on_desc, -> { order(arel_table[:on].desc) }
  scope :before, -> (ends_on) { where(arel_table[:on].lteq(ends_on)) }
  scope :deleted, -> { where.not(deleted_at: nil) }
  scope :not_deleted, -> { where(deleted_at: nil) }

  def self.tags
    taggings = ActsAsTaggableOn::Tagging.where(context: 'inventory_item_tags')
    ActsAsTaggableOn::Tag.joins(:taggings).merge(taggings).order(taggings_count: :desc).distinct
  end

  def self.order_options
    [["Purchase Date - Newest First", :on_desc], ["Purchase Date - Oldest First", :on_asc]]
  end

  def summary
    [name.presence, I18n.l(on).presence, inventory_item_tags.pluck(:name).join(', ')].compact.join(' - ')
  end

  def cost_in_dollars
    cost.to_i / 100.0
  end

  def cost_in_dollars=(amount)
    self.cost = amount.to_s.gsub(/[^-\d\.]/, '').to_f * 100
  end

  def value_in_dollars
    value.to_i / 100.0
  end

  def value_in_dollars=(amount)
    self.value = amount.to_s.gsub(/[^-\d\.]/, '').to_f * 100
  end

  def suggested_tags
    self.class.tags.where.not(id: inventory_item_tag_ids)
  end

end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController

  def index
    begin
      @ends_on = Date.strptime(params[:ends_on].to_s, '%Y-%m-%d')
    rescue ArgumentError, TypeError
      flash[:error] = 'Invalid date' if params[:ends_on].present?
      @ends_on = Time.zone.today
    end
    @inventory_items = InventoryItem.all
    @inventory_items = params[:deleted].to_i.nonzero? ? @inventory_items.deleted : @inventory_items.not_deleted
    @inventory_items = params[:order] == "on_asc" ? @inventory_items.order(on: :asc) : @inventory_items.on_desc
    @inventory_items = @inventory_items.page(params[:page])
    @inventory_items = @inventory_items.before(@ends_on.end_of_day) if params[:ends_on].present?
    if params[:term].present?
      term = "%#{params[:term].to_s.downcase}%"
      @inventory_items = @inventory_items.where(
        InventoryItem.arel_table[:name].matches(term).or(InventoryItem.arel_table[:description].matches(term))
      )
    end
    if params[:tag].present?
      @inventory_items = @inventory_items.tagged_with(params[:tag], on: :inventory_item_tags)
    end
  end

  def new
    @inventory_item = InventoryItem.new(safe_params)
    @inventory_item.on ||= Time.zone.today
  end

  def create
    @inventory_item = InventoryItem.new(safe_params)
    if @inventory_item.save
      redirect_to :inventory_items, notice: "#{InventoryItem.model_name.human} saved."
    else
      render :new
    end
  end

  def edit
    @inventory_item = InventoryItem.find(params[:id])
  end

  def update
    @inventory_item = InventoryItem.find(params[:id])
    if @inventory_item.update(safe_params)
      redirect_to :inventory_items, notice: "#{InventoryItem.model_name.human} saved."
    else
      render :edit
    end
  end

  def destroy
    InventoryItem.find(params[:id]).touch(:deleted_at)
    redirect_to :inventory_items, notice: "#{InventoryItem.model_name.human} deleted."
  end

  private

  def safe_params
    params.permit(inventory_item: [:name, :on, :description, :cost_in_dollars, :inventory_item_tag_list])[:inventory_item]
  end

  def authorized?
    Current.user&.parent?
  end

end

app/views/inventory_items/_form.html.haml
= form_for @inventory_item, html: { class: 'form-horizontal' } do |f|
  - if f.object.errors.any?
    .mb-3.alert.alert-danger
      = f.object.errors.full_messages.to_sentence
  .mb-3
    = f.label :name, class: 'form-label'
    = f.text_field :name, class: 'form-control'
  .row.mb-3
    .col-md-3
      = f.label :on, class: 'form-label'
      = f.date_field :on, class: 'form-control'
  .row.mb-3
    .col-md-3
      = f.label :cost_in_dollars, class: 'form-label'
      .input-group
        .input-group-text $
        = f.text_field :cost_in_dollars, class: 'form-control'
  .mb-3
    = f.label :description, class: 'form-label'
    = f.hidden_field :description, id: 'trix-editor-content'
    <trix-editor input="trix-editor-content"></trix-editor>
  .mb-3{ data: { controller: "tag-inserter" } }
    = f.label :inventory_item_tag_list, class: 'form-label'
    %p
      - f.object.suggested_tags.limit(9).each do |tag|
        = link_to tag.name, "#", data: { action: "tag-inserter#insert" }, class: 'btn btn-secondary btn-sm'
    = f.text_field :inventory_item_tag_list, value: f.object.inventory_item_tag_list.to_s, class: 'form-control',
      data: { tag_inserter_target: "input" }
  .mb-3
    = f.submit 'Save', class: 'btn btn-primary'
    = link_to 'Cancel', :inventory_items, class: 'btn btn-outline-secondary'

app/views/inventory_items/edit.html.haml
- title "Edit #{@inventory_item.name}"

- content_for :sidebar do

  .d-grid.gap-2
    = button_to @inventory_item, class: 'btn btn-danger', method: :delete, data: { turbo_confirm: "Are you sure you want to delete this #{InventoryItem.model_name.human}?" } do
      %i.bi-trash-fill
      Delete

= render 'form'

- if @inventory_item.photos.any?
  .row
    .col-md-12.photo-container
      = render @inventory_item.photos

app/views/inventory_items/index.html.haml
- title 'Household Inventory'

- content_for :sidebar do

  .d-grid.gap-2
    = link_to [:new, :inventory_item], class: 'btn btn-success' do
      %i.bi-plus-lg
      New Item

  %hr

  .text-center
    %strong
      #{pluralize number_with_delimiter(InventoryItem.not_deleted.count), 'item'}
      costing #{number_to_currency(@inventory_items.sum(:cost).to_d / 100)}

  - if InventoryItem.inventory_item_tag_counts.present?
    %hr
    - tag_counts = InventoryItem.tag_counts_on(:inventory_item_tags).order(taggings_count: :desc)
    = render partial: 'shared/tag_list', locals: { path: :inventory_items, tag_counts: tag_counts, total_count: InventoryItem.count }
    .mb-3

  %h3 Search
  = form_with url: :inventory_items, method: :get do |f|
    .mb-3
      = f.label :order
      = f.select :order, InventoryItem.order_options, { selected: params[:order] }, { class: 'form-control' }
    .mb-3
      = f.label :ends_on, 'Date'
      = f.date_field :ends_on, value: @ends_on, class: 'form-control'
    .mb-3
      = f.label :term
      = f.text_field :term, value: params[:term], class: 'form-control'
    .mb-3.d-grid.gap-2
      = f.submit 'Search', class: 'btn btn-primary'

%table.table.table-striped.table-dark
  %thead
    %tr
      %th= InventoryItem.human_attribute_name(:name)
      %th= InventoryItem.human_attribute_name(:on)
      %th= InventoryItem.human_attribute_name(:cost)
      %th= InventoryItem.human_attribute_name(:inventory_item_tag_list)
  %tbody
    - @inventory_items.each do |inventory_item|
      %tr
        %td= link_to inventory_item.name, [:edit, inventory_item], class: 'link-light text-decoration-none'
        %td= l inventory_item.on
        %td= number_to_currency inventory_item.cost_in_dollars
        %td
          - inventory_item.inventory_item_tag_list.each do |tag_name|
            %span.label.label-default{ style: 'margin-left: 0.5em' }
              = link_to tag_name, inventory_items_path(tag: tag_name), class: 'text-reset'

= paginate @inventory_items

app/views/inventory_items/new.html.haml
- title "New #{InventoryItem.model_name.human}"

= render 'form'