config/routes.rb
Rails.application.routes.draw do

  get "up", to: "rails/health#show", as: :rails_health_check

  namespace :api do
    resources :entries
  end

  resources :comments
  resources :decider_lists, shallow: true do
    resources :decider_list_items, only: %i[new create destroy]
  end
  resources :entries
  resources :entry_batches, only: %i[new create]
  resources :inventory_items
  resources :notes
  resources :pages
  resources :users
  resources :post_photos, only: %i[create destroy]
  resources :post_access_grants, only: %i[create]

  resources :print_batches, only: :index do
    collection do
      get :entries
      get :posts
    end
  end

  resources :posts

  resources :photos, except: %i[new create]
  resources :photo_batches, only: :create

  get 'pick', to: 'decider_list_picker#index'
  get 'pick/:id', to: 'decider_list_picker#new'
  post 'pick/:id', to: 'decider_list_picker#create'

  resources :sessions
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  get 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new', as: 'login'

  root to: 'pages#index'

end

app/models/post.rb
class Post < ApplicationRecord

  acts_as_taggable_on :post_tags

  has_many :comments
  has_many :post_photos
  has_many :photos, through: :post_photos

  before_create :auto_assign_photos

  validates :body, presence: true

  paginates_per 3

  scope :at_asc, -> { order(arel_table[:at].asc) }
  scope :at_desc, -> { order(arel_table[:at].desc) }
  scope :before, -> (ends_at) { where(arel_table[:at].lteq(ends_at)) }
  scope :past, -> { where(arel_table[:at].lteq(Time.zone.now)) }
  scope :future, -> { where(arel_table[:at].gt(Time.zone.now)) }


  def title
    Nokogiri::HTML(body).css('h1').text
  end

  def dated_title
    "#{I18n.l(at.to_date)} #{title}"
  end

  def self.tags
    taggings = ActsAsTaggableOn::Tagging.where(context: 'post_tags')
    ActsAsTaggableOn::Tag.joins(:taggings).merge(taggings).order(taggings_count: :desc).distinct
  end

  def suggested_tags
    self.class.tags.where.not(id: post_tag_ids)
  end

  private

  def auto_assign_photos
    if at.present?
      self.photos = Photo.where(hidden: false, created_at: at.beginning_of_day..at.end_of_day)
    end
    true
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    redirect_to Post.at_desc.past.first
  end

  def new
    @post = Post.new(safe_params)
    @post.at ||= Time.zone.now
  end

  def create
    @post = Post.new(safe_params)
    if @post.save
      redirect_to :posts, notice: 'Blog Post saved.'
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(safe_params)
      redirect_to :posts, notice: 'Post saved.'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to :posts, notice: 'Post destroyed.'
  end

  private

  def safe_params
    params.permit(post: [:at, :body, :post_tag_list])[:post]
  end

  def authorized?
    return true if Current.user.present?
    user = User.where.not(access_token: [nil, ""]).find_by!(access_token: params[:access_token])
    return false if action_name != 'show' || user.access_token_expires_at.past?
    user.log('blog')
    true
  end

end

app/views/posts/_form.html.haml
= form_with model: @post do |f|
  - if f.object.errors.any?
    .alert.alert-danger= f.object.errors.full_messages.to_sentence
  .mb-3
    = f.label :at, class: 'form-label'
    = f.datetime_field :at, class: 'form-control', tabindex: 1
  .mb-3
    = f.label :body, class: 'form-label'
    = f.hidden_field :body, id: 'trix-editor-content'
    <trix-editor input="trix-editor-content" autofocus="true" tabindex=2></trix-editor>
  .mb-3
    = f.submit 'Save', class: 'btn btn-primary', tabindex: 4

app/views/posts/_post.html.haml
- photos = post.photos.where(hidden: false).order(at: :asc)
- if photos.present?
  = render partial: "/shared/carousel_modal", locals: { photos: photos, modal_id: "post-#{post.id}-modal", carousel_id: "post-#{post.id}-carousel" }

.mb-4{ class: post.at.future? && 'bg-secondary p-3 rounded' }
  %h5.float-end.text-reset
    - css_class = post.at.future? ? 'fst-italic' : ''
    - if post.at.future?
      %span{ class: css_class } Scheduled for
    - if Current.user.present?
      = link_to l(post.at.to_date, format: :long), [:edit, post], class: [css_class, 'text-reset']
    - else
      = l(post.at.to_date, format: :long)

  .mb-3= post.body.html_safe

  - if photos.present?
    .d-flex.flex-wrap.align-items-center
      = render photos

  .row.mt-3
    .col-md-8
      = render post.comments.created_at_asc
      = form_with model: post.comments.new do |f|
        .mb-3
          = f.text_area :body, rows: 3, placeholder: 'Share your thoughts!', class: 'form-control', style: Current.user&.color.present? ? "border-color: #{Current.user.color}" : ''
        .mb-3
          = f.hidden_field :post_id
          = hidden_field_tag :access_token, params[:access_token]
          = f.submit 'Comment', class: 'btn btn-outline-success'

  .d-flex.justify-content-between
    - previous_post = Post.at_desc.where.not(id: post.id).find_by(at: Time.zone.at(0)..post.at)
    - if previous_post.present?
      = link_to "Previous: #{previous_post.title.presence || l(previous_post.at.to_date)}", previous_post, class: "btn btn-info"
    - next_post = Post.past.at_asc.where.not(id: post.id).find_by(at: post.at..Time.current)
    - if next_post.present?
      = link_to "Next: #{next_post.title.presence || l(next_post.at.to_date)}", next_post, class: "btn btn-info"

app/views/posts/edit.html.haml
- title 'Edit Blog Post'

- content_for :sidebar do
  - if @post.persisted?
    = button_to 'Delete', @post, method: :delete, class: 'btn btn-outline-danger', data: { turbo_confirm: "Are you sure you want to delete this blog post?" }

= render 'form'

- if (photos = @post.photos.at_asc).present?
  .d-flex.flex-wrap.align-items-center= render photos

app/views/posts/index.html.haml
- title 'Blog', false

- content_for :sidebar do

  - if current_user.parent?
    .d-grid.gap-2
      = link_to [:new, :post], class: 'btn btn-success' do
        %i.bi-plus-lg
        New Blog Post
    %hr

    %h3 Visitors
    %ul.list-unstyled
      - User.where.not(id: current_user.id).viewed_blog_at_desc.limit(8).each do |user|
        %li
          %strong= user.name
          &mdash;
          = time_tag user.viewed_blog_at, is: 'relative-time', title: l(user.viewed_blog_at) do
            = time_ago_in_words user.viewed_blog_at
            ago
    %hr

    %h3 Comments
    %ul.list-unstyled
      - Comment.created_at_desc.limit(5).each_with_index do |comment, i|
        %li
          %strong= comment.user.try(:name)
          &mdash;
          = time_tag comment.created_at, is: 'relative-time', title: l(comment.created_at) do
            = time_ago_in_words comment.created_at
            ago
    %hr

    %h3 Search
    = form_with url: :posts, method: :get do |f|
      .mb-3
        = f.label :ends_on, 'Date', class: 'form-label'
        = f.date_field :ends_on, value: @ends_on, class: 'form-control'
      .mb-3
        = f.label :term
        = f.text_field :term, value: params[:term], class: 'form-control', placeholder: 'Search term'
      .mb-3.d-grid
        = f.submit 'Search', class: 'btn btn-primary'
    %hr

  - if @past_posts.present?
    %h3 Calendar
    #calendar-accordion.accordion.text-dark
      - @past_posts.to_a.group_by { |post| post.at.year }.each do |year, posts|
        .accordion-item
          %h2.accordion-header
            %button.accordion-button{ type: 'button', class: year == Time.current.year ? '' : 'collapsed', data: { bs: { toggle: 'collapse', target: "#accordion-content-#{year}" } } }
              = year
          .accordion-collapse.collapse{ id: "accordion-content-#{year}", class: year == Time.current.year ? 'show' : '', data: { bs: { parent: '#calendar-accordion' } } }
            .list-group.list-group-flush
              - posts.each do |post|
                = link_to post.title.presence || l(post.at.to_date), post, class: 'list-group-item list-group-item-action'

  .d-grid.gap-2.mt-3
    = link_to :print_batches, class: 'btn btn-info' do
      %i.bi-printer
      Print by Year

  - if current_user.parent? && Post.post_tag_counts.present?
    %hr
    - tag_counts = Post.tag_counts_on(:post_tags).order(taggings_count: :desc)
    = render partial: 'shared/tag_list', locals: { path: :posts, tag_counts: tag_counts }

= render @future_posts if current_user.parent?

- if @past_posts.empty?
  .alert.alert-warning
    %h2 Nothing to see here.
    %p Apparently, we're not that interesting. :)
    = link_to 'Show all posts', :posts
- else
  - @past_posts = @past_posts.page(params[:page])
  = render @past_posts
  = paginate @past_posts

app/views/posts/index.rss.haml
!!! XML
%rss{:version => '2.0'}
  %channel
    %title Daniel &amp; Erika's blog
    %link= posts_url
    %description
      The (private) blog of Daniel and Erika Esplin in St. George, Utah.
    %language en-us
    %pubDate= Time.now.rfc822

    - @past_posts.each do |post|
      %item
        %title= post.title
        %description
          %p= post.title
          %p
            - if post.photos.count > 0
              Includes #{pluralize(post.photos.count, 'picture')}!
            - else
              No pictures. :(
        %link= posts_url
        %guid= post.id
        %pubDate= post.at.rfc822

app/views/posts/new.html.haml
- title 'New Blog Post'

= render 'form'

app/views/posts/show.html.haml
- title 'Blog', false

- if Current.user.present?

  - content_for :sidebar do

    .d-grid.gap-2
      = link_to [:new, :post], class: 'btn btn-success' do
        %i.bi-plus-lg
        New Blog Post
    %hr

    %h3 Visitors
    %ul.list-unstyled
      - User.guest.order(viewed_blog_at: :desc).each do |user|
        %li.d-flex.justify-content-between.mb-2
          %strong= user.name
          - if user.viewed_blog_at.present?
            = time_tag user.viewed_blog_at, is: 'relative-time', title: l(user.viewed_blog_at) do
              = time_ago_in_words user.viewed_blog_at
              ago
          - grant = PostAccessGrant.new(user_id: user.id, user: user, post_id: @post.id)
          = form_with model: grant, data: { turbo: false }, html: { target: :_blank, rel: "noopener" } do |f|
            = f.hidden_field :post_id
            = f.hidden_field :user_id
            = f.submit 'Email', class: 'btn btn-warning'
    %hr

      .d-flex.justify-content-between
        %h5.d-inline Photo count
        %span #{@post.photos.count}
    %hr

    - all_posts = Post.at_desc
    - cache(all_posts) do
      %h3 Calendar
      #calendar-accordion.accordion.text-dark
        - all_posts.to_a.group_by { |post| post.at.year }.each do |year, posts|
          .accordion-item
            %h2.accordion-header
              %button.accordion-button{ type: 'button', class: year == Time.current.year ? '' : 'collapsed', data: { bs: { toggle: 'collapse', target: "#accordion-content-#{year}" } } }
                = year
            .accordion-collapse.collapse{ id: "accordion-content-#{year}", class: year == Time.current.year ? 'show' : '', data: { bs: { parent: '#calendar-accordion' } } }
              .list-group.list-group-flush
                - posts.each do |post|
                  - css_classes = 'list-group-item list-group-item-action'
                  - if post.at.future?
                    - next unless Current.user.parent?
                    - css_classes << ' list-group-item-secondary'
                  = link_to post, class: css_classes do
                    - if post.at.future?
                      %i.bi-calendar3{ title: "Unpublished" }
                      &nbsp;
                    = post.title.presence || l(post.at.to_date)

    .d-grid.gap-2.mt-3
      = link_to :print_batches, class: 'btn btn-info' do
        %i.bi-printer
        Print by Year

= render @post